### ISSUE TITLE
typo: "that" should be "than"

### ISSUE THREAD

**Issue by mauke** [Tux/Release-Checklist#14]
https://metacpan.org/release/HMBRAND/Release-Checklist-0.17/view/Checklist.pm#Multiple-perl-versions

> [...] is probably a better choice *that* 2.1.

https://metacpan.org/release/HMBRAND/Release-Checklist-0.17/view/Checklist.pm#Release-tests

> Other *that* doing all these tests [...]

These should be "than" instead.

**Comment by Tux** [comment]
Done
