### ISSUE TITLE
broken formatting in Tickets

### ISSUE THREAD

**Issue by mauke** [Tux/Release-Checklist#16]
The bugtracker examples under https://metacpan.org/release/HMBRAND/Release-Checklist-0.17/view/Checklist.pm#Tickets have broken formatting. They use a code paragraph for the file name, but a plain text paragraph for the (JSON) contents. Replicated in Markdown syntax, it looks like this:

>     META.yml
>
> ================================================================================ resources: bugtracker: https://github.com/Tux/Release-Checklist/issues
>
>     META.json
>
> ================================================================================ "resources" : { "bugtracker" : { "web" : "https://github.com/Tux/Release-Checklist/issues" } }

**Comment by Tux** [comment]
Thanks, fixed
