### ISSUE TITLE
Can't generate Checklist.html

### ISSUE THREAD

**Issue by mauke** [Tux/Release-Checklist#18]
I made changes to Checklist.md, but Checklist.html cannot be rebuilt:
```
perl md2html.pl
Converting Checklist.md to Checklist.html
Cannot find file -o at /usr/bin/multimarkdown line 127.
multimarkdown failed!
make: *** [Makefile:924: Checklist.html] Error 2
```
What version of `multimarkdown` are you using that understands a `-o` option?

**Comment by Tux** [comment]
FWIW I've just pushed a commit that prefers `cmark` over `multimarkdown` if it is available
```
$ multimarkdown --version

MultiMarkdown 6 v6.6.0
Copyright © 2016 - 2020 Fletcher T. Penney.
```
```
$ cmark --version
cmark 0.30.3 - CommonMark converter
(C) 2014-2016 John MacFarlane
```
Alternatives welcome :)
They both seem rather old

**Comment by mauke** [comment]
Ah, thanks. The `multimarkdown` on Ubuntu comes from libtext-multimarkdown-perl (-> https://metacpan.org/pod/Text::MultiMarkdown), which is a lot older.

**Comment by Tux** [comment]
Newest uses `pandoc`. If noit available, `cmark`, if not available `multimarkdown`.
What I see is that none add the required HTML header section, so that is added for all.

Does that work for you too? Should I guard the `multimarkdown` against missing `-o`?

**Comment by mauke** [comment]
This looks good. Thank you!
